import { Stack } from "@chakra-ui/layout";
import type { NextPage } from "next";
import { useContext, useState } from "react";
import Head from "next/head";
import CoinRateCard from "../components/CoinRateCard";
import AccSummary from "../components/AccSummary";
import InteractionPanel from "../components/InteractionPanel";
import { tokenData } from "../utils/dummyData";
import Layout, { AppContext } from "../components/Layout";

const Home: NextPage = () => {
  const [isInteractOpen, setIsInteractOpen] = useState(false);

  const { isUserConnected } = useContext(AppContext);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        {isUserConnected ? <AccSummary /> : null}
        {isUserConnected && isInteractOpen ? <InteractionPanel setIsInteractOpen={setIsInteractOpen} /> : null}
        <Stack as="section" spacing={2} minW="100%">
          {tokenData.map((tknInfo) => (
            <CoinRateCard
              key={tknInfo.ticker}
              ticker={tknInfo.ticker}
              imgUrl={tknInfo.imgUrl}
              saveRate={tknInfo.saveRate}
              borrRate={tknInfo.borrRate}
              setIsInteractOpen={setIsInteractOpen}
            />
          ))}
        </Stack>
      </Layout>
    </>
  );
};

export default Home;
