import { Container, Stack } from "@chakra-ui/layout";
import type { NextPage } from "next";
import Head from "next/head";
import Navbar from "../components/Navbar";
import CoinRateCard from "../components/CoinRateCard";
import AccSummary from "../components/AccSummary";

const tokenData = [
  {
    ticker: "wBTC",
    imgUrl: "/wBTC.svg",
    saveRate: 3.86,
    borrRate: 5.39,
  },
  {
    ticker: "ETH",
    imgUrl: "/ETH.svg",
    saveRate: 1.95,
    borrRate: 3.75,
  },
  {
    ticker: "BAT",
    imgUrl: "/BAT.svg",
    saveRate: 18.16,
    borrRate: 21.59,
  },
];

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <Container as="main" maxW="container.lg" p={5} d="flex" flexDir="column" alignItems="center">
        <AccSummary />
        <Stack as="section" spacing={2} minW="100%">
          {tokenData.map((tknInfo) => (
            <CoinRateCard
              key={tknInfo.ticker}
              ticker={tknInfo.ticker}
              imgUrl={tknInfo.imgUrl}
              saveRate={tknInfo.saveRate}
              borrRate={tknInfo.borrRate}
            />
          ))}
        </Stack>
      </Container>

      <footer></footer>
    </div>
  );
};

export default Home;
